<template>
    <div class="detailpage-cd">
        <div class="detailpage-box">
            <!--        分类详情头部-->
            <div class="detailpage-header" @click="_scroll">
                <ul>
                    <li>
                        <i class="fa fa-chevron-left" @click="_back"></i>
                    </li>
                    <li>
                        <p>{{detail}}</p>
                    </li>
                    <li>
                        <div>
                            <i class="fa fa-search"></i>
                            <i class="fa fa-cart-arrow-down"></i>
                        </div>
                    </li>
                </ul>
            </div>
            <!--        分类详情滚动条-->
            <div class="detailpage-scroll">
                <ul>
                    <li v-for="(cl,cls) in keep" :key="cls">{{cl}}</li>
                </ul>
            </div>
            <!--        分类详情选择-->
            <div class="detailpage-option">
                <ul id="ulBox">
                    <li>
                        <span>最新</span><i class="fa fa-angle-down"></i>
                    </li>
                    <li>
                        <span>全部</span><i class="fa fa-angle-down"></i>
                    </li>
                </ul>
                <div class="detailpage-model-lis">
                    <div class="detailpage-new">
                        <span class="detailpage-col">最新</span>
                        <span>最热</span>
                    </div>
                    <div class="detailpage-all">
                        <span class="detailpage-col">全部</span>
                        <span>课程</span>
                        <span>实战</span>
                    </div>
                </div>
            </div>

        </div>
        <!--        详情列表-->
        <div class="detailpage-option-list">
            <div class="detailpage-option-listbox" v-for="(de,bls) in deatilcont" :key="bls">
                <ul>
                    <li v-for="(li,lis) in de.detailList" :key="lis">
                        <router-link :to="`/categorydetailpage/${lis}`">
                            <img :src="li.src" alt="">
                            <div class="detailpage-list-cont">
                                <h3>{{li.tit}}</h3>
                                <p>
                                    <strong>{{li.free}}</strong>
                                    <strong>{{li.dif}}</strong>
                                    <i></i>
                                    <span>{{li.per}}</span>
                                </p>
                                <p class="detailpage-price">
                                    <span>{{li.pri}}</span>
                                </p>
                            </div>
                        </router-link>
                    </li>
                </ul>
            </div>
            <div class="detailpage-option-noll">
                <p>没有更多数据了</p>
            </div>
        </div>

        <div class="detailpage-bla"></div>
    </div>
</template>

<script>
    import $ from "jQuery"
    export default {
        name: "ClassifyDetailPage",
        data(){
            return{
                deatilcont:[
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            }
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            }
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            }
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            }
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            }
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            }
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            }
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            }
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },

                        ]
                    },
                    {
                        detailList:[
                           {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            }
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            }
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            }
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5becd5ad0001b89306000338-360-202.jpg",
                                tit:"Girde布局基础",
                                free:"免费",
                                dif:"中级",
                                per:"7877",
                                pri:""
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/58f57d200001461105400300-360-202.jpg",
                                tit:"前端跳槽面试必备技巧",
                                free:"",
                                dif:"中级",
                                per:"4004",
                                pri:"￥266"
                            }
                        ]
                    },
                    {
                        detailList:[
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/5c0493ce000126b106000338-360-202.jpg",
                                tit:"5G时代Vlog原型系统开发",
                                free:"免费",
                                dif:"入门",
                                per:"5814",
                                pri:"￥299"
                            },
                            {
                                src:"http://img1.sycdn.imooc.com/szimg/59b8a486000107fb05400300-360-202.jpg",
                                tit:"商业级支付宝小程序入门与实践",
                                free:"",
                                dif:"初级",
                                per:"235",
                                pri:"￥299"
                            }
                        ]
                    },
                ],
                classs:[
                    ["不限","HTML/CSS","JavaScrpit","Vue.js","React.JS","Angular",
                        "Node.js","jQuery","Bootstrap","Sass/Less","WebApp","小程序","前端工具",
                        "CSS","Html5","CSS3"],
                    ["不限","Java","SpringBoot","SpringCloud","Python","爬虫",
                        "Django","Tornado","Go","PHP","C","C++","C#",
                        "Ruby"],
                    ["不限","Android","iOS","Reactnative","WEEX"],
                    ["不限","算法与数据结构","数学","算法"],
                    ["不限","微服务","区块链","以太坊","人工智能","机器学习",
                        "深度学习","计算机视觉","自然语言法处理","数据分析&挖掘"],
                    ["不限","大数据","Hadoop","Spark","Hbase","云计算",
                        "Aws","Docker","Kubernetes"],
                    ["不限","运维","自动化运维","运维工具","Linux","测试",
                        "功能测试","性能测试","自动化测试","接口测试","安全测试"],
                    ["不限","MySQL","Redis","MongoDB","Oracle","SQL Server",
                        "NoSql"],
                    ["不限","模型制作","动效动画","设计基础","设计工具","APPUI设计",
                        "产品交互"],
                    ["不限","Unity 3D","Cocos2d-x"],
                ],
                listt:["前端开发","后端开发","移动开发","算法&数学","前沿技术","云计算&大数据","运维&测试","数据库","UI设计&多媒体","游戏","前端开发","后端开发","移动开发","算法&数学","前沿技术","云计算&大数据","运维&测试","数据库","UI设计&多媒体","游戏"],
                detail:[],
                keep:[]
            }
        },
       created(){
           let {id} = this.$route.params;
           this.detail = this.listt[id],
           this.keep = this.classs[id]
       },
        mounted(){
            $(".detailpage-scroll > ul > li").eq(1).addClass("bgc");
            $(".detailpage-option-listbox").eq(1).addClass("bl");
            this._scroll();
            this._show();
            this._active()
        },
        methods:{
            _show(){
                $(function () {
                    $(".detailpage-scroll > ul > li").click(function () {
                        $(this).addClass("bgc").siblings().removeClass("bgc");
                        $(".detailpage-option-listbox").eq($(this).index()).addClass("bl").siblings().removeClass("bl");
                    })
                    $("#ulBox > li").click(function () {
                        $(".detailpage-model-lis").stop().slideToggle();
                        $(".detailpage-bla").stop().fadeToggle()
                        if($(this).index()===0){
                            $(".detailpage-new").stop().toggle()
                        }
                        if($(this).index()===1){
                            $(".detailpage-all").stop().toggle()
                        }
                    });
                    $(".detailpage-bla").click(function () {
                        $(this).fadeOut();
                        $(".detailpage-model-lis").stop().slideUp(100)
                    })
                })
            },
            _back(){
                this.$router.go("-1")
            },
            _scroll(){
                $(".detailpage-option-list").scroll(function() {
                    var scroHei = $(".detailpage-option-list").scrollTop();//滚动的高度
                    if (scroHei>30) {
                        $(".detailpage-header").fadeOut();
                    } else {
                        $(".detailpage-header").fadeIn();
                    }
                })
            },
            _active(){
                $(function () {
                    $("#ulBox > li").click(function () {
                        $("#ulBox > li > i").eq($(this).index()).toggleClass("fa-angle-down fa-angle-up");
                    })
                })
            },
        }
    }
</script>

<style scoped>
    @import "../assets/css/ClassifyDetailPage.css"
</style>