<template>
    <div class="classifyBox">
        <classify-header></classify-header>
        <!--        分类盒子-->
        <div class="category-ify-box">
            <!--            左侧导航-->
            <div class="category-box-lis">
                <ul class="category-ulBox">
                    <li v-for="(lis,llis) in list" :key="llis">
                        <p>{{lis}}</p>
                    </li>
                </ul>
            </div>
            <!--            右侧导航-->
            <div class="category-box-cont">
                <ul class="category-rUlbox">
                    <li v-for="(c,rlis) in url" :key="rlis">
                        <a href="" v-for="(a,alis) in c.show" :key="alis">
                            <img :src="a" alt="">
                        </a>
                        <!--                        右侧盒子容器-->
                        <div class="category-right-box">
                            <div v-for="(p,lix) in c.lis" :key="lix">
                                <router-link :to="`/categorydetailpage/${rlis}`">
                                    <img :src="p.src" alt="" >
                                    <p>{{p.tit}}</p>
                                </router-link>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <!--底部-->
        <classify-footer/>
    </div>
</template>

<script>
    import $ from "jQuery"
    import Header from "../components/index/Header";
    import Footer from "../components/common/Footer"
    export default {
        name: "Classify",
        components:{
            ClassifyHeader:Header,
            ClassifyFooter:Footer

        },
        mounted(){
            this._active();
            $(".category-rUlbox > li").eq(0).addClass("now");
            $(".category-ulBox > li > p").eq(0).addClass("col");
        },
        data(){
            return {
                list:["前端开发","后端开发","移动开发","算法&数学","前沿技术","云计算&大数据","运维&测试","数据库","UI设计&多媒体","游戏","算法&数学","前沿技术","云计算&大数据"],
                url:[
                    {
                        "show":["./img/classify/b1.png"],
                        "lis":[
                            {
                                "src":"./img/classify/1.png",
                                "tit":"HTML/CSS"
                            },
                            {
                                "src":"./img/classify/2.png",
                                "tit":"JavaScrpit"
                            },
                            {
                                "src":"./img/classify/3.png",
                                "tit":"Vue.js"
                            },
                            {
                                "src":"./img/classify/4.png",
                                "tit":"React.JS"
                            },
                            {
                                "src":"./img/classify/5.png",
                                "tit":"Angular"
                            },
                            {
                                "src":"./img/classify/6.png",
                                "tit":"Node.js"
                            },
                            {
                                "src":"./img/classify/7.png",
                                "tit":"jQuery"
                            },
                            {
                                "src":"./img/classify/8.png",
                                "tit":"Bootstrap"
                            },
                            {
                                "src":"./img/classify/9.png",
                                "tit":"Sass/Less"
                            },
                            {
                                "src":"./img/classify/10.png",
                                "tit":"WebApp"
                            },
                            {
                                "src":"./img/classify/11.png",
                                "tit":"小程序"
                            },
                            {
                                "src":"./img/classify/12.png",
                                "tit":"前端工具"
                            },
                            {
                                "src":"./img/classify/13.png",
                                "tit":"CSS"
                            },
                            {
                                "src":"./img/classify/14.png",
                                "tit":"Html5"
                            },
                            {
                                "src":"./img/classify/15.png",
                                "tit":"CSS3"
                            }
                        ]
                    },
                    {
                        "show":["./img/classify/b2.png",
                                "./img/classify/b3.png",
                                "./img/classify/b4.png"],
                        "lis":[
                            {
                                "src":"./img/classify/16.png",
                                "tit":"Java"
                            },
                            {
                                "src":"./img/classify/17.png",
                                "tit":"SpringBoot"
                            },
                            {
                                "src":"./img/classify/18.png",
                                "tit":"SpringCloud"
                            },
                            {
                                "src":"./img/classify/19.png",
                                "tit":"Python"
                            },
                            {
                                "src":"./img/classify/20.png",
                                "tit":"爬虫"
                            },
                            {
                                "src":"./img/classify/21.png",
                                "tit":"Django"
                            },
                            {
                                "src":"./img/classify/22.png",
                                "tit":"Tornado"
                            },
                            {
                                "src":"./img/classify/23.png",
                                "tit":"Go"
                            },
                            {
                                "src":"./img/classify/24.png",
                                "tit":"PHP"
                            },
                            {
                                "src":"./img/classify/25.png",
                                "tit":"C"
                            },
                            {
                                "src":"./img/classify/26.png",
                                "tit":"C++"
                            },
                            {
                                "src":"./img/classify/27.png",
                                "tit":"C#"
                            },
                            {
                                "src":"./img/classify/28.png",
                                "tit":"Ruby"
                            }
                        ]
                    },
                    {
                        "show":["./img/classify/b5.png"],
                        "lis":[
                            {
                                "src":"./img/classify/29.png",
                                "tit":"Android"
                            },
                            {
                                "src":"./img/classify/30.png",
                                "tit":"iOS"
                            },
                            {
                                "src":"./img/classify/31.png",
                                "tit":"React native"
                            },
                            {
                                "src":"./img/classify/32.png",
                                "tit":"WEEX"
                            }
                        ]
                    },
                    {
                        "show":[],
                        "lis":[
                            {
                                "src":"./img/classify/33.png",
                                "tit":"算法与数据结构"
                            },
                            {
                                "src":"./img/classify/34.png",
                                "tit":"数学"
                            },
                            {
                                "src":"./img/classify/35.png",
                                "tit":"算法"
                            }
                        ]
                    },
                    {
                        "show":[],
                        "lis":[
                            {
                                "src":"./img/classify/36.png",
                                "tit":"微服务"
                            },
                            {
                                "src":"./img/classify/37.png",
                                "tit":"区块链"
                            },
                            {
                                "src":"./img/classify/38.png",
                                "tit":"以太坊"
                            },
                            {
                                "src":"./img/classify/39.png",
                                "tit":"人工智能"
                            },
                            {
                                "src":"./img/classify/40.png",
                                "tit":"机器学习"
                            },
                            {
                                "src":"./img/classify/41.png",
                                "tit":"深度学习"
                            },
                            {
                                "src":"./img/classify/42.png",
                                "tit":"计算机视觉"
                            },
                            {
                                "src":"./img/classify/43.png",
                                "tit":"自然语言法处理"
                            },
                            {
                                "src":"./img/classify/44.png",
                                "tit":"数据分析&挖掘"
                            }
                        ]
                    },
                    {
                        "show":[],
                        "lis":[
                            {
                                "src":"./img/classify/45.png",
                                "tit":"大数据"
                            },
                            {
                                "src":"./img/classify/46.png",
                                "tit":"Hadoop"
                            },
                            {
                                "src":"./img/classify/47.png",
                                "tit":"Spark"
                            },
                            {
                                "src":"./img/classify/48.png",
                                "tit":"Hbase"
                            },
                            {
                                "src":"./img/classify/49.png",
                                "tit":"Storm"
                            },
                            {
                                "src":"./img/classify/50.png",
                                "tit":"云计算"
                            },
                            {
                                "src":"./img/classify/51.png",
                                "tit":"Aws"
                            },
                            {
                                "src":"./img/classify/52.png",
                                "tit":"Docker"
                            },
                            {
                                "src":"./img/classify/53.png",
                                "tit":"Kubernetes"
                            }
                        ]
                    },
                    {
                        "show":[],
                        "lis":[
                            {
                                "src":"./img/classify/54.png",
                                "tit":"运维"
                            },
                            {
                                "src":"./img/classify/55.png",
                                "tit":"自动化运维"
                            },
                            {
                                "src":"./img/classify/56.png",
                                "tit":"运维工具"
                            },
                            {
                                "src":"./img/classify/57.png",
                                "tit":"Linux"
                            },
                            {
                                "src":"./img/classify/58.png",
                                "tit":"测试"
                            },
                            {
                                "src":"./img/classify/59.png",
                                "tit":"功能测试"
                            },
                            {
                                "src":"./img/classify/60.png",
                                "tit":"性能测试"
                            },
                            {
                                "src":"./img/classify/61.png",
                                "tit":"自动化测试"
                            },
                            {
                                "src":"./img/classify/62.png",
                                "tit":"接口测试"
                            },
                            {
                                "src":"./img/classify/63.png",
                                "tit":"安全测试"
                            }
                        ]
                    },
                    {
                        "show":[],
                        "lis":[
                            {
                                "src":"./img/classify/64.png",
                                "tit":"MySQL"
                            },
                            {
                                "src":"./img/classify/65.png",
                                "tit":"Redis"
                            },
                            {
                                "src":"./img/classify/66.png",
                                "tit":"MongoDB"
                            },
                            {
                                "src":"./img/classify/67.png",
                                "tit":"Oracle"
                            },
                            {
                                "src":"./img/classify/68.png",
                                "tit":"SQL Server"
                            },
                            {
                                "src":"./img/classify/69.png",
                                "tit":"NoSql"
                            }
                        ]
                    },
                    {
                        "show":[],
                        "lis":[
                            {
                                "src":"./img/classify/70.png",
                                "tit":"模型制作"
                            },
                            {
                                "src":"./img/classify/71.png",
                                "tit":"动效动画"
                            },
                            {
                                "src":"./img/classify/72.png",
                                "tit":"设计基础"
                            },
                            {
                                "src":"./img/classify/73.png",
                                "tit":"设计工具"
                            },
                            {
                                "src":"./img/classify/74.png",
                                "tit":"APPUI设计"
                            },
                            {
                                "src":"./img/classify/75.png",
                                "tit":"产品交互"
                            }
                        ]
                    },
                    {
                        "show":[],
                        "lis":[
                            {
                                "src":"./img/classify/76.png",
                                "tit":"Unity 3D"
                            },
                            {
                                "src":"./img/classify/77.png",
                                "tit":"Cocos2d-x"
                            }
                        ]
                    }
                ]
            }
        },
        methods:{
            _active(){
                $(function () {
                    $(".category-ulBox > li").click(function () {
                        $(".category-rUlbox > li").eq($(this).index()).addClass("now").siblings().removeClass("now");
                        $(this).children("p").addClass("col").parent().siblings().children("p").removeClass("col")
                    })
                })
            },
        }
    }
</script>

<style scoped>
    /* @import "../assets/css/Classify.css" */
</style>